export const materias = [
 {id: 1, nome: 'Desenvolvimento para Servidores II | IDS-002 +', desc: 'Conceitos e evolução das tecnologias de programação de servidores. Recursos da linguagem escolhida para servidores na Internet. Padrões de projetos. Integração com sistemas (Google Maps API, Twitter, entre outros)'},
 {id: 2, nome: 'Desenvolvimento para dispositivos móveis I | ISW-011 +', desc: 'Introdução e conceitos. Recursos disponíveis para dispositivos móveis na linguagem de marcação de textos. Uso de algum ambiente de desenvolvimento: configuração do ambiente; emulação de dispositivos móveis nos computadores pessoais; interface gráfica; serviços disponíveis; banco de dados nos dispositivos. Desenvolvimento de aplicações que utilizam dados de geolocalização. Integração entre sistemas remotos.'},
 {id: 3, nome: 'Inglês V | LIN-500 +', desc: 'Aprofundamento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa.'},
 {id: 4, nome: 'Negócios e Marketing Eletrônicos | AGM-004 +',  desc: 'Conceitos de marketing e de marketing digital. O comportamento do consumidor on-line. Marketing de conteúdo. Marketing nas mídias sociais. E-mail marketing. Marketing viral. Publicidade on-line. Pesquisa de marketing on-line. Marketing e os negócios na Internet. Estudos de caso.'},
 {id: 5, nome: 'Projeto de prototipagem e testes de Usabilidade | ISW-012 +', desc: 'Conceitos, métodos de prototipagem e ferramentas de teste de protótipos. Conceitos de usabilidade e estratégias de design. Métodos de teste de usabilidade. Planejamento de teste de usabilidade. Recrutamento. Projeto de usabilidade. Plano de teste. Sessão de teste de usabilidade. Análise de dados. Comunicação dos resultados. Variação de técnicas.'},
 {id: 6, nome: 'Projeto do trabalho de graduação em Sistemas | TTG-401 +',desc: 'Conceito de portfólio no âmbito da educação superior. Planejamento e organização de portfólios.'},
 {id: 7, nome: 'Tópicos Especiais em Sistemas para Internet II | ITE-004 +',  desc: 'Recursos e aplicações da tecnologia escolhida.'},
];
